# Use root/example as user/pwpw credentials
version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: pwpw
      MYSQL_DATABASE: deliver
      #MYSQL_USER
      #MYSQL_PASSWORD
    volumes:
      - deliverDb:/app/data/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "80:8080"

  deliver:
    build: .
    restart: no
    ports:
      - "8080:8080"
    environment:
      dbhost: db
      dbuser: root
      dbpass: pwpw
    depends_on:
      - db

volumes:
    deliverDb:
      external: true